### ISSUE TITLE
not able to pull up after import

### ISSUE THREAD

**Issue by jamesdboone** [splunkalicious/conf2019#1]
Tried to install in new splunk 8.0.

Seemed to install ok, but no objects show up, no app in app menu, don't see how to pull up the demo.

**Comment by splunkalicious** [comment]
Hi James,

It looks like some MacOs files included in the zip are preventing proper install via the GUI.

If you unzip the file into splunk/etc/apps/conf_2019 the app should appear after a restart.

I'm going to tidy up the zip once I'm back in Melbourne, but please let me know if unzipping the app into etc/apps works for you.

Kind regards
Matthew Moore

**Comment by jamesdboone** [comment]
Thanks!  After following your instructions, I also found a typo with the 'default' tag in local/data/ui/nav/default.xml.  After fixing and restarting, all is good...
